### ISSUE TITLE
this pluggin does not support on mobile devices

### ISSUE THREAD

**Issue by krishna-hytech** [marcj/jquery-selectBox#170]
Hello Guys,

I have used this type of plugin and select box drop-down open very well.

but problem is that default style not looks good on tablet and phone device.

I have used this type of property.

$('select').selectBox();

    $('select').selectBox('settings', {
                                    'mobile': 'true',
                    'menuTransition':'fade'

    });

What should I do ?

**Comment by ruben1** [comment]
true should be a boolean and not a string

**Comment by krishna-hytech** [comment]
hi
I have used this code

**Comment by krishna-hytech** [comment]
![e30e3b0946532fc071b90649e771da177a3ba1001c1de2aecd pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13568019/8981879/870e321e-36d9-11e5-86f0-480b1a01809f.jpg)

**Comment by krishna-hytech** [comment]
hi
I have used this code.
$('select').selectBox();
$('select').selectBox('settings', {
                                    mobile: true
 });
But this plugin looks bad. 
please see the attachment image for tablet.
![tablet-screenshot](https://cloud.githubusercontent.com/assets/13568019/8981943/20e9cef2-36da-11e5-8edb-1b5c7fd2defb.PNG)

Can you give the reference link in which this select box plugin work well on tablet and mobile device. ?
There is any solutions.  ?

**Comment by krishna-hytech** [comment]
hi
I have used this code.
$('select').selectBox();
$('select').selectBox('settings', {
mobile: true
});
But this plugin looks bad. ( All years ,all topic etc. looks bad. only)
please see the attachment image for tablet.
![issues-scrrenshot](https://cloud.githubusercontent.com/assets/13568019/9006708/0975dad0-37a8-11e5-89da-42b92dc51728.png)

**Comment by krishna-hytech** [comment]
hi
There is any solutions ?
